name: _Unit-Tests

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:

  backend-trpc:
    runs-on: ubuntu-latest
    services:
      dynamodb:
        image: amazon/dynamodb-local:3.0.0
        ports:
          - 8000/tcp
        options: >-
          --health-cmd="curl http://localhost:8000/shell"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-node
      - run: pnpm run test:unit:ci
        working-directory: ./backend-trpc
        env:
          THATBLOG_DYNAMODB_ENDPOINT: http://localhost:${{ job.services.dynamodb.ports[8000] }}
          SKIP_TESTCONTAINERS_DYNAMODB: 'yes'

  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init-node
      - run: pnpm run --filter './packages/*' --if-present test:unit:ci
